In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.DataFrame()

In [4]:
df['age'] = np.random.randint(21,60,1500)
df['salary'] = np.random.randint(10000,60000,1500)
df['city'] = np.random.choice(['Mumbai','Noida','Banglore','Hyderabad','Chennai'],1500,p=[0.2, 0.2, 0.3, 0.2,0.1])
df['attrition'] = np.random.choice(['Yes','No'],1500,p=[0.3,0.7])

In [5]:
np.random.choice(['21,60,1500','sdsds'],1500)

array(['21,60,1500', 'sdsds', 'sdsds', ..., '21,60,1500', 'sdsds',
       '21,60,1500'], dtype='<U10')

In [6]:
np.random.choice(['Mumbai','Noida','Banglore','Hyderabad','Chennai'],1500,p=[0.2, 0.2, 0.3, 0.2,0.1])

array(['Chennai', 'Banglore', 'Banglore', ..., 'Banglore', 'Banglore',
       'Hyderabad'], dtype='<U9')

In [7]:
df.head()

   age  salary       city attrition
0   44   10293  Hyderabad        No
1   47   13175    Chennai        No
2   50   49527   Banglore        No
3   41   27640      Noida       Yes
4   52   37688     Mumbai       Yes

In [30]:
df.style.format({'salary':'${:,.0f}','age':'{:.001%}'})

In [26]:
df.style.format({'salary':'${:,.0f}','age':'{:0>3d}'})

In [31]:
df.head(10).style.highlight_max()

In [32]:
df.head(10).style.highlight_min()

In [35]:
df.head(10).style.highlight_min(subset=['salary','age'],color='lightgreen')

In [38]:
df.head(10).style.highlight_max(subset=['salary','age'],color='lightgreen').highlight_min(subset=['salary','age'],color='lightpink')

In [40]:
df.head(10).style.highlight_between(left=20000, right=50000, subset='salary')

In [61]:
f'{round(15488,-3):,}'

'15,000'

In [73]:
pd.date_range(start='2020-01-01', end='2020-01-31', freq='d').to_list()

[Timestamp('2020-01-01 00:00:00', freq='D'),
 Timestamp('2020-01-02 00:00:00', freq='D'),
 Timestamp('2020-01-03 00:00:00', freq='D'),
 Timestamp('2020-01-04 00:00:00', freq='D'),
 Timestamp('2020-01-05 00:00:00', freq='D'),
 Timestamp('2020-01-06 00:00:00', freq='D'),
 Timestamp('2020-01-07 00:00:00', freq='D'),
 Timestamp('2020-01-08 00:00:00', freq='D'),
 Timestamp('2020-01-09 00:00:00', freq='D'),
 Timestamp('2020-01-10 00:00:00', freq='D'),
 Timestamp('2020-01-11 00:00:00', freq='D'),
 Timestamp('2020-01-12 00:00:00', freq='D'),
 Timestamp('2020-01-13 00:00:00', freq='D'),
 Timestamp('2020-01-14 00:00:00', freq='D'),
 Timestamp('2020-01-15 00:00:00', freq='D'),
 Timestamp('2020-01-16 00:00:00', freq='D'),
 Timestamp('2020-01-17 00:00:00', freq='D'),
 Timestamp('2020-01-18 00:00:00', freq='D'),
 Timestamp('2020-01-19 00:00:00', freq='D'),
 Timestamp('2020-01-20 00:00:00', freq='D'),
 Timestamp('2020-01-21 00:00:00', freq='D'),
 Timestamp('2020-01-22 00:00:00', freq='D'),
 Timestamp('2020-01-23 00:00:00', freq='D'),
 Timestamp('2020-01-24 00:00:00', freq='D'),
 Timestamp('2020-01-25 00:00:00', freq='D'),
 Timestamp('2020-01-26 00:00:00', freq='D'),
 Timestamp('2020-01-27 00:00:00', freq='D'),
 Timestamp('2020-01-28 00:00:00', freq='D'),
 Timestamp('2020-01-29 00:00:00', freq='D'),
 Timestamp('2020-01-30 00:00:00', freq='D'),
 Timestamp('2020-01-31 00:00:00', freq='D')]

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['attrition']), df['attrition'], test_size=0.2, random_state=33)

In [17]:
X_train

      age  salary       city
1118   24   45991      Noida
996    38   23797   Banglore
427    34   45383  Hyderabad
495    22   26371      Noida
858    41   31338  Hyderabad
...   ...     ...        ...
1225   26   40739     Mumbai
658    36   50138      Noida
578    58   45407   Banglore
391    25   51335  Hyderabad
1044   24   38680     Mumbai

[1200 rows x 3 columns]

In [ ]:
from sklearn.compose import ColumnTransformer